import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { createGroup } from '../api/conversations';
import { listFriends, type Friend } from '../api/friends';

export default function CreateGroupPage() {
  const navigate = useNavigate(); const [friends, setFriends] = useState<Friend[]>([]); const [selected, setSelected] = useState<string[]>([]); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [filter, setFilter] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { void listFriends(100, 0).then((r) => setFriends(r.data?.friends ?? [])).catch(() => setError('Could not load friends')); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setSaving(true); setError(''); try { const result = await createGroup({ name: name.trim(), description: description.trim() || undefined, member_ids: selected }); if (!result.success || !result.data) throw new Error(result.error || 'Could not create group'); navigate(`/conversations/${result.data.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not create group'); } finally { setSaving(false); } };
  const shown = friends.filter((friend) => friend.FriendName.toLowerCase().includes(filter.toLowerCase()));
  return <div className="app-shell min-h-screen"><header className="app-header"><div className="mx-auto max-w-3xl px-4 py-4"><Link to="/conversations" className="text-blue-400">← Conversations</Link></div></header><main className="mx-auto max-w-3xl px-4 py-8"><h1 className="text-3xl font-bold text-white">Create a group</h1><form onSubmit={submit} className="app-card mt-6 space-y-5 p-5"><label className="block text-sm text-slate-300">Name<input value={name} onChange={(e) => setName(e.target.value)} maxLength={100} required className="app-input mt-2 w-full px-4 py-3" /></label><label className="block text-sm text-slate-300">Description (optional)<textarea value={description} onChange={(e) => setDescription(e.target.value)} maxLength={2000} className="app-input mt-2 min-h-24 w-full px-4 py-3" /></label><div><label className="text-sm text-slate-300">Add friends</label><input value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="Search your friends" className="app-input mt-2 w-full px-4 py-3" /><div className="mt-2 max-h-64 overflow-y-auto rounded-xl border border-[#25364d]">{shown.map((friend) => <label key={friend.FriendID} className="flex cursor-pointer items-center gap-3 border-b border-[#25364d] p-3 last:border-0"><input type="checkbox" checked={selected.includes(friend.FriendID)} onChange={() => setSelected((ids) => ids.includes(friend.FriendID) ? ids.filter((id) => id !== friend.FriendID) : [...ids, friend.FriendID])} /><span>{friend.FriendName}</span></label>)}</div></div>{error && <p className="text-sm text-red-300">{error}</p>}<button disabled={saving || !name.trim()} className="primary-button w-full px-5 py-3 font-semibold disabled:opacity-50">{saving ? 'Creating...' : `Create group${selected.length ? ` with ${selected.length} friend${selected.length === 1 ? '' : 's'}` : ''}`}</button></form></main></div>;
}
