import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { changePassword, deactivateAccount, getProfile } from '../api/auth';
import { useAuth } from '../context/AuthContext';

export default function ProfilePage() {
  const { user, updateUser, logout } = useAuth(); const navigate = useNavigate();
  const [username, setUsername] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { void getProfile().then((result) => { if (result.success && result.data) { setUsername(result.data.username); setEmail(result.data.email); } else setError(result.error || 'Could not load profile'); }).catch(() => setError('Could not load profile')).finally(() => setLoading(false)); }, []);
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); const result = await updateUser({ username, email }); setSaving(false); if (result.success) setMessage('Profile updated.'); else setError(result.error || 'Profile update failed'); };
  const savePassword = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const result = await changePassword({ password }); if (!result.success) setError(result.error || 'Password change failed'); else { setPassword(''); setMessage('Password changed. You may need to sign in again.'); await logout(); navigate('/login', { replace: true }); } } catch { setError('Password change failed'); } finally { setSaving(false); } };
  const deactivate = async () => { if (!window.confirm('Deactivate your account? This cannot be undone here.')) return; setSaving(true); setError(''); try { const result = await deactivateAccount(); if (!result.success) setError(result.error || 'Could not deactivate account'); else { await logout(); navigate('/login', { replace: true }); } } catch { setError('Could not deactivate account'); } finally { setSaving(false); } };
  if (loading) return <div className="app-shell flex min-h-screen items-center justify-center text-slate-300">Loading...</div>;
  return <div className="app-shell min-h-screen p-4 sm:p-8"><div className="app-card mx-auto max-w-lg p-6 sm:p-8"><Link to="/friends" className="text-sm font-semibold text-blue-400 hover:text-blue-300">← Back to friends</Link><h1 className="mt-5 mb-7 text-2xl font-bold text-white">Your profile</h1>{error && <div className="mb-4 rounded-xl border border-red-900/60 bg-red-950/40 p-3 text-red-300">{error}</div>}{message && <div className="mb-4 rounded-xl border border-emerald-900/60 bg-emerald-950/40 p-3 text-emerald-300">{message}</div>}<form onSubmit={saveProfile} className="space-y-4"><h2 className="font-semibold text-slate-200">Profile details</h2><input value={username} onChange={(e) => setUsername(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="Username" /><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="Email" /><button disabled={saving} className="primary-button px-4 py-3 text-sm font-semibold disabled:opacity-50">Save profile</button></form><form onSubmit={savePassword} className="space-y-4 border-t border-[#25364d] mt-8 pt-8"><h2 className="font-semibold text-slate-200">Change password</h2><input type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="New password" /><button disabled={saving} className="primary-button px-4 py-3 text-sm font-semibold disabled:opacity-50">Change password</button></form><div className="border-t border-[#25364d] mt-8 pt-8"><h2 className="font-semibold text-red-300">Danger zone</h2><p className="my-2 text-sm text-slate-400">Deactivate your account and sign out of all sessions.</p><button onClick={() => void deactivate()} disabled={saving || !user} className="rounded-xl border border-red-700 px-4 py-3 text-sm font-semibold text-red-300 hover:bg-red-950/50 disabled:opacity-50">Deactivate account</button></div></div></div>;
}
