import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { changePassword, deactivateAccount, getProfile } from '../api/auth';
import { useAuth } from '../context/AuthContext';

export default function ProfilePage() {
  const { user, updateUser, logout } = useAuth(); const navigate = useNavigate();
  const [username, setUsername] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { void getProfile().then((result) => { if (result.success && result.data) { setUsername(result.data.username); setEmail(result.data.email); } else setError(result.error || 'Could not load profile'); }).catch(() => setError('Could not load profile')).finally(() => setLoading(false)); }, []);
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); const result = await updateUser({ username, email }); setSaving(false); if (result.success) setMessage('Profile updated.'); else setError(result.error || 'Profile update failed'); };
  const savePassword = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const result = await changePassword({ password }); if (!result.success) setError(result.error || 'Password change failed'); else { setPassword(''); setMessage('Password changed. You may need to sign in again.'); await logout(); navigate('/login', { replace: true }); } } catch { setError('Password change failed'); } finally { setSaving(false); } };
  const deactivate = async () => { if (!window.confirm('Deactivate your account? This cannot be undone here.')) return; setSaving(true); setError(''); try { const result = await deactivateAccount(); if (!result.success) setError(result.error || 'Could not deactivate account'); else { await logout(); navigate('/login', { replace: true }); } } catch { setError('Could not deactivate account'); } finally { setSaving(false); } };
  if (loading) return <div className="min-h-screen flex items-center justify-center">Loading...</div>;
  return <div className="min-h-screen bg-gray-50 p-4"><div className="max-w-lg mx-auto bg-white rounded-lg shadow-md p-8"><Link to="/friends" className="text-purple-600">← Back</Link><h1 className="text-2xl font-bold mt-4 mb-6">Your profile</h1>{error && <div className="mb-4 p-3 bg-red-100 text-red-700 rounded">{error}</div>}{message && <div className="mb-4 p-3 bg-green-100 text-green-700 rounded">{message}</div>}<form onSubmit={saveProfile} className="space-y-4"><h2 className="font-semibold">Profile details</h2><input value={username} onChange={(e) => setUsername(e.target.value)} required className="w-full px-3 py-2 border rounded-md" placeholder="Username" /><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="w-full px-3 py-2 border rounded-md" placeholder="Email" /><button disabled={saving} className="px-4 py-2 bg-purple-600 text-white rounded-md disabled:opacity-50">Save profile</button></form><form onSubmit={savePassword} className="space-y-4 border-t mt-8 pt-8"><h2 className="font-semibold">Change password</h2><input type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required className="w-full px-3 py-2 border rounded-md" placeholder="New password" /><button disabled={saving} className="px-4 py-2 bg-purple-600 text-white rounded-md disabled:opacity-50">Change password</button></form><div className="border-t mt-8 pt-8"><h2 className="font-semibold text-red-700">Danger zone</h2><p className="text-sm text-gray-600 my-2">Deactivate your account and sign out of all sessions.</p><button onClick={() => void deactivate()} disabled={saving || !user} className="px-4 py-2 border border-red-600 text-red-600 rounded-md disabled:opacity-50">Deactivate account</button></div></div></div>;
}
