import ThemePicker from '../components/ThemePicker';
import { useDialogs } from '../context/DialogContext';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { changePassword, deactivateAccount, getProfile } from '../api/auth';
import { useAuth } from '../context/AuthContext';

export default function ProfilePage() {
  const { confirm } = useDialogs();
  const { user, updateUser, logout } = useAuth(); const navigate = useNavigate();
  const [username, setUsername] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { void getProfile().then((result) => { if (result.success && result.data) { setUsername(result.data.username); setEmail(result.data.email); } else setError(result.error || 'Could not load profile'); }).catch(() => setError('Could not load profile')).finally(() => setLoading(false)); }, []);
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); const emailChanged = email.trim().toLowerCase() !== user?.email.toLowerCase(); const result = await updateUser({ username, email }); setSaving(false); if (result.success && emailChanged) { await logout(); navigate(`/verify?email=${encodeURIComponent(email.trim().toLowerCase())}`, { replace: true }); } else if (result.success) setMessage('Profile updated.'); else setError(result.error || 'Profile update failed'); };
  const savePassword = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const result = await changePassword({ password }); if (!result.success) setError(result.error || 'Password change failed'); else { setPassword(''); setMessage('Password changed. You may need to sign in again.'); await logout(); navigate('/login', { replace: true }); } } catch { setError('Password change failed'); } finally { setSaving(false); } };
  const deactivate = async () => { if (!await confirm('Deactivate your account? This cannot be undone here.')) return; setSaving(true); setError(''); try { const result = await deactivateAccount(); if (!result.success) setError(result.error || 'Could not deactivate account'); else { await logout(); navigate('/login', { replace: true }); } } catch { setError('Could not deactivate account'); } finally { setSaving(false); } };
  if (loading) return <div className="app-shell flex min-h-screen items-center justify-center text-secondary">Loading...</div>;
  return <div className="app-shell min-h-screen p-4 sm:p-8"><div className="app-card mx-auto max-w-lg p-6 sm:p-8"><Link to="/conversations" className="text-sm font-semibold text-accent hover-accent">← Back to chats</Link><h1 className="mt-5 mb-7 text-2xl font-bold text-primary">Your profile</h1>{error && <div className="mb-4 rounded-xl border border-danger bg-danger-soft p-3 text-danger">{error}</div>}{message && <div className="mb-4 rounded-xl border border-accent bg-accent-soft p-3 text-accent">{message}</div>}<ThemePicker /><form onSubmit={saveProfile} className="space-y-4"><h2 className="font-semibold text-primary">Profile details</h2><input value={username} onChange={(e) => setUsername(e.target.value)} required className="app-input w-full px-3 py-3" aria-label="Username" placeholder="Username" /><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="app-input w-full px-3 py-3" aria-label="Email" placeholder="Email" /><button disabled={saving} className="primary-button px-4 py-3 text-sm font-semibold disabled:opacity-50">Save profile</button></form><form onSubmit={savePassword} className="space-y-4 border-t border-theme mt-8 pt-8"><h2 className="font-semibold text-primary">Change password</h2><input type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required className="app-input w-full px-3 py-3" aria-label="New password" placeholder="New password" /><button disabled={saving} className="primary-button px-4 py-3 text-sm font-semibold disabled:opacity-50">Change password</button></form><div className="border-t border-theme mt-8 pt-8"><h2 className="font-semibold text-danger">Danger zone</h2><p className="my-2 text-sm text-secondary">Deactivate your account and sign out of all sessions.</p><button onClick={() => void deactivate()} disabled={saving || !user} className="rounded-xl border border-danger px-4 py-3 text-sm font-semibold text-danger hover-surface disabled:opacity-50">Deactivate account</button></div></div></div>;
}
