import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { confirmPasswordReset, requestPasswordReset } from '../api/auth';

export default function RecoveryPage() {
  const [email, setEmail] = useState(''); const [token, setToken] = useState(''); const [password, setPassword] = useState(''); const [sent, setSent] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const request = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await requestPasswordReset({ email }); if (result.success) { setSent(true); setMessage(result.data?.message || 'If the account exists, recovery instructions were sent.'); } else setError(result.error || 'Could not request recovery'); } catch { setError('Could not request recovery'); } finally { setLoading(false); } };
  const confirm = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await confirmPasswordReset({ token, password }); if (result.success) setMessage('Password reset. You can now sign in.'); else setError(result.error || 'Invalid or expired recovery token'); } catch { setError('Invalid or expired recovery token'); } finally { setLoading(false); } };
  return <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4"><div className="max-w-md w-full p-8 bg-white rounded-lg shadow-md"><h1 className="text-2xl font-bold mb-6">Recover password</h1>{error && <div className="mb-4 p-3 bg-red-100 text-red-700 rounded">{error}</div>}{message && <div className="mb-4 p-3 bg-green-100 text-green-700 rounded">{message}</div>}<form onSubmit={request} className="space-y-4"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="w-full px-3 py-2 border rounded-md" placeholder="Email" /><button disabled={loading} className="w-full py-2 bg-purple-600 text-white rounded-md disabled:opacity-50">{sent ? 'Send again' : 'Send recovery instructions'}</button></form><form onSubmit={confirm} className="space-y-4 border-t mt-8 pt-8"><input value={token} onChange={(e) => setToken(e.target.value)} required className="w-full px-3 py-2 border rounded-md" placeholder="Recovery token" /><input type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required className="w-full px-3 py-2 border rounded-md" placeholder="New password" /><button disabled={loading} className="w-full py-2 bg-gray-700 text-white rounded-md disabled:opacity-50">Reset password</button></form><Link to="/login" className="block mt-4 text-purple-600">Back to login</Link></div></div>;
}
