import { useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { confirmPasswordReset, requestPasswordReset } from '../api/auth';

export default function RecoveryPage() {
  const [params] = useSearchParams();
  const [email, setEmail] = useState(''); const [token, setToken] = useState(() => params.get('token') ?? ''); const [password, setPassword] = useState(''); const [sent, setSent] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const request = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await requestPasswordReset({ email }); if (result.success) { setSent(true); setMessage(result.data?.message || 'If the account exists, recovery instructions were sent.'); } else setError(result.error || 'Could not request recovery'); } catch { setError('Could not request recovery'); } finally { setLoading(false); } };
  const confirm = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await confirmPasswordReset({ token, password }); if (result.success) setMessage('Password reset. You can now sign in.'); else setError(result.error || 'Invalid or expired recovery token'); } catch { setError('Invalid or expired recovery token'); } finally { setLoading(false); } };
  return <div className="app-shell flex min-h-screen items-center justify-center p-4"><div className="app-card w-full max-w-md p-7 sm:p-9"><h1 className="mb-7 text-2xl font-bold text-primary">Recover password</h1>{error && <div className="mb-4 rounded-xl border border-danger bg-danger-soft p-3 text-danger">{error}</div>}{message && <div className="mb-4 rounded-xl border border-accent bg-accent-soft p-3 text-accent">{message}</div>}<form onSubmit={request} className="space-y-4"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="Email" /><button disabled={loading} className="primary-button w-full py-3 font-semibold disabled:opacity-50">{sent ? 'Send again' : 'Send recovery instructions'}</button></form><form onSubmit={confirm} className="space-y-4 border-t border-theme mt-8 pt-8"><input value={token} onChange={(e) => setToken(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="Recovery token" /><input type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="New password" /><button disabled={loading} className="w-full rounded-xl bg-raised py-3 font-semibold text-primary hover-surface disabled:opacity-50">Reset password</button></form><Link to="/login" className="mt-5 block text-sm font-semibold text-accent hover-accent">Back to login</Link></div></div>;
}
