import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { confirmVerification, requestVerification } from '../api/auth';

export default function VerificationPage() {
  const [email, setEmail] = useState(''); const [token, setToken] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await requestVerification(email); if (result.success) setMessage(result.data?.message || 'If the account exists, verification instructions were sent.'); else setError(result.error || 'Could not request verification'); } catch { setError('Could not request verification'); } finally { setLoading(false); } };
  const verify = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await confirmVerification(token); if (result.success) setMessage('Account verified.'); else setError(result.error || 'Invalid or expired verification token'); } catch { setError('Invalid or expired verification token'); } finally { setLoading(false); } };
  return <div className="app-shell flex min-h-screen items-center justify-center p-4"><div className="app-card w-full max-w-md p-7 sm:p-9"><h1 className="mb-7 text-2xl font-bold text-white">Verify account</h1>{error && <div className="mb-4 rounded-xl border border-red-900/60 bg-red-950/40 p-3 text-red-300">{error}</div>}{message && <div className="mb-4 rounded-xl border border-emerald-900/60 bg-emerald-950/40 p-3 text-emerald-300">{message}</div>}<form onSubmit={submit} className="space-y-4"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="Email" /><button disabled={loading} className="primary-button w-full py-3 font-semibold disabled:opacity-50">Send verification instructions</button></form><form onSubmit={verify} className="space-y-4 border-t border-[#25364d] mt-8 pt-8"><input value={token} onChange={(e) => setToken(e.target.value)} required className="app-input w-full px-3 py-3" placeholder="Verification token" /><button disabled={loading} className="w-full rounded-xl bg-[#1c3049] py-3 font-semibold text-slate-200 hover:bg-[#25405f] disabled:opacity-50">Verify account</button></form><Link to="/login" className="mt-5 block text-sm font-semibold text-blue-400 hover:text-blue-300">Back to login</Link></div></div>;
}
